Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip python3-dev libpq-dev gcc
    pip3 install psycopg2 Django
  SHELL

  config.vm.provision "file", source: "recent_files.txt", destination: "/home/vagrant/recent_files.txt"
end
